package pl.nowakprojects.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import pl.nowakprojects.entities.Book;
import pl.nowakprojects.repositories.BookRepository;

import java.util.List;

/**
 * Created by Mateusz on 08.04.2017.
 */
@RestController
@RequestMapping("/db/book")
public class BookDatabaseController {

    @Autowired
    BookRepository bookRepository;

    @RequestMapping("/findall")
    public List<Book> findAll(){
        return bookRepository.findAll();
    }

    @RequestMapping("/add")
    public String addBook(@RequestBody Book book){
        book.setId(null); //Id should be autogenerated
        bookRepository.save(book);
        return "We now have " + bookRepository.count() + " books!";
    }

    @RequestMapping("/get/{id}")
    public Book find(@PathVariable Integer id){
        return bookRepository.findOne(id);
    }

    @RequestMapping("/find/{name}")
    public List<Book> find(@PathVariable String name){
        return bookRepository.findByNameIgnoreCaseContaining(name);
    }
}
